### ISSUE TITLE
Question, figwheel worklfow?

### ISSUE THREAD

**Issue by geksilla** [dvcrn/proton#13]
Hi @dvcrn, do you use figwheel during development? I've succeed on figwheel activation and got hot code reload and another nice features, but it's a bit hacky. Could you please share your dev workflow with figwheel? Thanks.

**Comment by geksilla** [comment]
[Here is](https://github.com/geksilla/proton/tree/feature/fighweel-dev-server/dev_server) how I achieved it.

**Comment by dvcrn** [comment]
I'm currently not using figwheel but it definitely looks interesting. I didn't know code reload was possible inside atom. 

I'm experimenting over at the [shadow-build branch](https://github.com/dvcrn/proton/tree/shadow-build) with a new build tool that could get rid of some of the cljsbuild flaws. Maybe @thheller can give some insights if hot reload is possible

**Comment by geksilla** [comment]
I recently updated [how-to](https://github.com/geksilla/proton/tree/feature/fighweel-dev-server/dev_server) for Mac OS. I've tested it on Linux also and it works for me. If you are interesting try the [dev-server branch](https://github.com/geksilla/proton/tree/feature/fighweel-dev-server)

**Comment by thheller** [comment]
When I run `lein figwheel dev-server` I get

```clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/utils.clj:1:1)```

How do I get that running?

**Comment by thheller** [comment]
Nevermind, upgrading `lein` fixed that.

**Comment by thheller** [comment]
@geksilla got it working, although live-reloading doesn't really work. figwheel reloads the file but breaks things in the process. (eg. `spc` menu is empty after reloading `proton.lib.atom`).

I sort of expected that, or am I just doing something wrong and this works for you?

**Comment by geksilla** [comment]
@thheller, yes I also hit this problem. But when I defined [these two atoms](https://github.com/dvcrn/proton/blob/master/src/proton/core.cljs#L40-L41) with **defonce** macro and reload editor it works fine. Sometimes live-reload breaks app states but in general it works pretty well.

**Comment by dvcrn** [comment]
Since proton is mainly stateless (the state is getting overriden on each editor start), can't we just do something like:

```
atom.packages.disablePackage("proton-mode");
atom.packages.enablePackage("proton-mode");
````

This would force reload proton from disk with all changes

**Comment by dvcrn** [comment]
Hm. Doesn't seem to work, atom doesn't actually reload file changes. Ok then maybe we really need to live eval code

**Comment by dvcrn** [comment]
Ok thanks to the amazing work by @thheller, the `shadow-build` branch now has full support for hot live-reload! 

I will try to get this merged by today but no more window reloading!
