### ISSUE TITLE
Top folder in open file dialogue is obscured by underline

### ISSUE THREAD

**Issue by Lknechtli** [dvcrn/proton#133]
![image](https://cloud.githubusercontent.com/assets/4392704/12889384/a734e000-ce4c-11e5-8626-d4223f49a8d9.png)

OS: Ubuntu 15.10

**Comment by jessejanderson** [comment]
Had the same thing on OS X, switched to a different theme as it seemed to be an issue with the material theme.

**Comment by dvcrn** [comment]
hmm odd. We are currently thinking of swapping material with [nucleus](https://atom.io/themes/nucleus-dark-ui) as it seems to be a lot more adaptable as a default theme. 

Besides that, I think we could hard-tweak the theme with some shipped css files

**Comment by jessejanderson** [comment]
:+1: I'm a fan of Nucleus as a UI since it adapts so well to any syntax theme you want to use.

**Comment by dvcrn** [comment]
New theme is out in [latest release](https://github.com/dvcrn/proton/releases/tag/v0.8.0)
