### ISSUE TITLE
Initial package installation randomly aborts

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/proton#140]
I'm not sure why or when this happens but I had it twice that when a lot of packages are due to be installed, it only installs a few of them, reports 'success' and on the next start installs the rest. Maybe we have a timeout somewhere?

**Comment by dvcrn** [comment]
This definitely happens on all new installations. For some tests it showed `21` new packages and after all were installed and atom restarted, it installed `11` more. Something is fishy here.

**Comment by mli-max** [comment]
I had issue with `autocomplete ruby`. I put it to disabled, proton said "deinstalling" but after restart again "installing"

**Comment by dvcrn** [comment]
Seems to no longer be relevant. I'm going ahead with closing this.
