### ISSUE TITLE
Can't use spaces in iex

### ISSUE THREAD

**Issue by jessejanderson** [dvcrn/proton#148]
Currently, the `iex` package is impossible to use since you can't type spaces without pulling up the proton keymap menu.

**Comment by dvcrn** [comment]
That brings up a interesting problem. I think we should allow layers to exclude certain pane selectors from the `SPC` chain. What do you think @geksilla?

**Comment by geksilla** [comment]
@dvcrn, agree need to provide some helpers to prevent such problems.
