### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by Lknechtli** [dvcrn/proton#159]
Proton should have some :)

Possibly utilize PR and issue templates - for instance a checklist of steps to take before submitting an issue, and what information to include in an issue
For example:

- [ ] Have you tried running proton with a minimal .proton file, and if so, what are the minimal settings required to reproduce the issue?

On a similar train of thought, I highly recommend using something like git-flow.

**Comment by dvcrn** [comment]
Messed the auto-close hook up. PR is available here https://github.com/dvcrn/proton/pull/167
