### ISSUE TITLE
Setting "core" options in `~/.atom/config.cson`

### ISSUE THREAD

**Issue by spencerlyon2** [dvcrn/proton#16]
I'm trying to apply the theme/syntax highlighting I had in my atom config from within proton and am having problems.

I've added the proper packages to the `:additional-packages` section and in `:configuration` I have included

```
    ["core.themes" ["isotope-ui"
                    "tomorrow-night-eighties-syntax"]]
```

When I launch a new atom (proton) window the console tells me

```
Setting core.themes to ["isotope-ui" "tomorrow-night-eighties-syntax"]
```

But then when I do `cat ~/.atom/config.cson` I see `core: {}`

Is there supposed to be another way to do this?

**Comment by dvcrn** [comment]
Hrrm this indeed doesn't work. I think it might be that the value is a vector / array which I didn't think was possible. 

I'll see if I can submit a hotfix for this

**Comment by dvcrn** [comment]
Ok, vectors are now being parsed correctly as javascript arrays. Tested it with a few themes and seems to work. Let me know if you still have problems

**Comment by spencerlyon2** [comment]
Fixed, thanks!
