### ISSUE TITLE
Proposal: change [b]+buffer to [tab]+tabs

### ISSUE THREAD

**Issue by DanTheColoradan** [dvcrn/proton#162]
Thoughts?

Atom doesn't have buffers in the traditional vim sense ~~and [b] for build makes sense in terms of the "build layer"~~.

This probably goes against #67, which makes sense to me since atom is different than both vim and emacs.

**Comment by DanTheColoradan** [comment]
[tab] -> +tabs
-----------------------
[tab] -> previous tab
[n] -> next tab
[p] -> previous tab
[c] -> create new tab
.... others?

**Comment by dvcrn** [comment]
Hmm I'm against this. I don't consider the `tab` key a key that is part of the normal keyset and see it more similar to mod / special keys. I think it's a bit odd if most keybindings follow a character mnemonic and a essential key is suddenly on a special key that needs the weakest finger to activate. 

Another thing is that proton is more or less a vim emulation system that expands on the idea of doing everything in command mode and using insert only for short bursts of text. Buffer just fits better in that case for me.

Just my 2 cents. What do you think @geksilla ?

**Comment by geksilla** [comment]
Agree with @dvcrn. `tab` key is just modifier. I don't think that is mnemonic `tab` key as UI tab would be correct. For sure atom not vim or emacs and buffer may confuse some people since atom's editor layout based on panes and tabs. But I'm gonna to stay with `b` prefix. For build prefix I feel more comfortable `c` as `compile` and associated with mode key bindings.

**Comment by Lknechtli** [comment]
another option for build would be to put it under the project category, since it's generally a project-wide action

**Comment by DanTheColoradan** [comment]
Thanks all :) @Lknechtli I'll consider that option next.

**Comment by geksilla** [comment]
:+1: for project category like `SPC p c` mnemonic to [__p__]roject [__c__]ompile

**Comment by dvcrn** [comment]
One other idea I have for the future is allowing to remind entire categories inside .proton. That way everyone can have their favorite mnemonic, but until then we will still need some time :)
