### ISSUE TITLE
TODOs for only current branch

### ISSUE THREAD

**Issue by Lknechtli** [dvcrn/proton#166]
No idea how much effort this would take.

When working on a large projects with many TODO's scattered through the comments, it would be useful to be able to filter to the TODO comments that were added on the current branch (or in files modified on the current branch).  Generally I only care TODO's that I added while working on a bugfix/feature, and not those in files that I haven't even touched.

Since the package we use for TODO's doesn't interface with source control at all, I don't think this feature request really belongs there, but I'm not really sure how we'd go about adding this.

**Comment by dvcrn** [comment]
Filtering only the files that are changed is pretty straight forward with a little bit of shell magic, finding TODOs as well but yeah, I don't think this should be part of proton core. This should go into a separate plugin that deals with this or just fork the current TODO plugin. Proton could then integrate that.
