### ISSUE TITLE
nvAtom for tools/notes

### ISSUE THREAD

**Issue by DanTheColoradan** [dvcrn/proton#181]
I've been using [nvatom](https://atom.io/packages/nvatom) for writing notes like crazy and it has been great. I feel like it would be a solid package to include with proton. Thoughts?

I believe it would be a great addition because it doesn't require you learn anything new. As you type, it searches your notes to find anything similar. If you hit enter, it creates a new note for you. So even though it is based on [Notational Velocity](http://notational.net), it doesn't require you subscribe to NV to use it.

Also, if y'all like this idea, what key preference? All of your notes go to one folder, so it isn't project specific. It's also works best when used from anywhere (i.e. not just markdown files), so it shouldn't go in mode. Would [n] -> +notes or perhaps [_] -> +meta be right?

**Comment by richarddewit** [comment]
I guess things like this should be categorized in Applications (<kbd>SPC a</kbd>) so <kbd>SPC a n</kbd> would be notes. I like the idea :)

**Comment by dvcrn** [comment]
I would also put it under `a n`. Though we currently don't have anything in there. if it is purely in atom, does it makes sense to put it under `a` or should we keep that for only stuff that interfaces with external applications?

**Comment by richarddewit** [comment]
> does it makes sense to put it under <kbd>a</kbd>

I think it does. Who knows what other "external applications" are going to be added? Better to categorize beforehand than having to move them when something new gets added.

> should we keep that for only stuff that interfaces with external applications?

Yes

**Comment by geksilla** [comment]
Fixed in #221.

**Comment by smldis** [comment]
@geksilla  please reopen since nvatom package is not existing anymore.

**Comment by geksilla** [comment]
@smldis, see #289
