### ISSUE TITLE
Add slight delay to which-key popup

### ISSUE THREAD

**Issue by richarddewit** [dvcrn/proton#184]
When typing keys in rapid succession, the blinking of the which-key popup is quite weird. Could there be a (modifiable/toggle-able) delay before showing the which-key popup?

Currently in Spacemacs:
``` elisp
   ...
   ;; Which-key delay in seconds. The which-key buffer is the popup listing
   ;; the commands bound to the current keystroke sequence. (default 0.4)
   dotspacemacs-which-key-delay 0.4
   ...
```

*__Note:__ I'd love to contribute with PRs, but unfortunately I lack every knowledge of Clojure..*

**Comment by dvcrn** [comment]
> Note: I'd love to contribute with PRs, but unfortunately I lack every knowledge of Clojure..

proton is a fun project to get started :)

**Comment by richarddewit** [comment]
I seem to be learning at least some of the syntax from fiddling with the `.proton` config file, but Clojure wasn't on my list of "Languages I might be using at some time" :)

**Comment by geksilla** [comment]
added in #205
