### ISSUE TITLE
How to add custom syntax highlighting theme?

### ISSUE THREAD

**Issue by gazsp** [dvcrn/proton#186]
I've got my own syntax highlighting theme that I'd like to use with Atom / Proton.

How do I go about getting Proton to load it without deleting it as an 'orphaned package' each time Atom starts?

Also, a FAQ would be really good for Proton :-)

**Comment by dvcrn** [comment]
How are you currently managing your own syntax styles? Did you pack them into a custom package? 

Usually you can just add the name of that package into `additional-packages` to tell atom that it's legit and not orphaned. If a package has no connection from either the users .proton file or from other layers, it will get marked as 'to remove'.
