### ISSUE TITLE
`fd` produces no output or action in insert mode

### ISSUE THREAD

**Issue by xtian** [dvcrn/proton#188]
I was hoping that <kbd>fd</kbd> would exit insert mode like in Spacemacs, but typing these two keys in succession seems to neither invoke an action nor produce any output.

This is on a fresh installation of Atom 1.7.1.

**Comment by dvcrn** [comment]
I think atom has a very fast timeout. Proton comes with bindings for exiting insert mode (like in spacemacs) out of the box but it depends on the vim mode you use. 
If you use vim-mode-plus (what proton does out of the box) you should be good. If you use normal vim mode you need to change the fd binding here: https://github.com/dvcrn/proton/blob/master/plugin/templates/proton.edn#L99-L103

I am using this keybinding very intensively and can definitely say that it works :)

**Comment by xtian** [comment]
I haven't changed any of the default configuration that Proton sets. It doesn't seem to matter how fast or slow I hit those keys.

I noticed that if I just hit <kbd>d</kbd> by itself it is input into the buffer immediately, but if I hit <kbd>f</kbd> there is a full second delay before anything happens.

Here's a screen capture of the behavior I'm describing:
https://dl.dropboxusercontent.com/u/55092740/Untitled.mov

**Comment by richarddewit** [comment]
Possibly due to the upgrade to Atom 1.7. I've noticed `SPC TAB` not working in 1.7 as well..

**Comment by dvcrn** [comment]
Ouch. A major version change could indeed be the issue. I'm gonna check. ping @geksilla as well

**Comment by dvcrn** [comment]
I upgraded to 1.7. `SPC TAB` is broken but `f d` for terminating insert mode seems to work completely fine for me

**Comment by xtian** [comment]
@dvcrn https://gist.github.com/xtian/427c9fc1fa8c79e79f168bfce52c0cad

**Comment by xtian** [comment]
Ah yeah looks like it was fixed in 92f2367. Is there a way to update the .proton file when a new version is released?

**Comment by dvcrn** [comment]
Sadly not currently. You can do a diff between the template and your ~/.proton file to see the difference but that's not automated yet.
