### ISSUE TITLE
How can someone control settings of packages?

### ISSUE THREAD

**Issue by kibin** [dvcrn/proton#202]
Is there any option to control settings in installed packages? Maybe it’s unrelated, but if I manually change settings in packages they get resetted every time I reload atom.

**Comment by dvcrn** [comment]
Yes this should be documented better.

**Comment by dvcrn** [comment]
yes this should be documented better. 

Each setting for each package has a certain configuration string. You can find that after changing a setting and opening your atom config file. 

You can then put these strings inside your `.proton` file to freeze it in that state. For example, this is what it says in my config file:
```
  "linter-clojure":
    clojureExecutablePath: "/Users/david/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar"
    javaExecutablePath: "/usr/bin/java"
```

The equivalent lines in the `.proton` file look like this:
```clj
    ["linter-clojure.javaExecutablePath" "/usr/bin/java"]
    ["linter-clojure.clojureExecutablePath" "/Users/david/.m2/repository/org/clojure/clojure/1.7.0/clojure-1.7.0.jar"]
```

**Comment by kibin** [comment]
Thanks!
