### ISSUE TITLE
Package checking is case sensitive, but Atom package names are not

### ISSUE THREAD

**Issue by quarterto** [dvcrn/proton#204]
I noticed this when adding [Hydrogen](https://atom.io/packages/hydrogen) as an additional package. I added `:hydrogen` to the list, restarted, and it installed. However, because its name in `package.json` is `Hydrogen`, Proton would attempt to reinstall it on every launch.

**Comment by geksilla** [comment]
I've checked this issue and it's a bit confusing. Basically `apm` is not case sensitive but atom's `package api` is. For example `Parinfer` package:
```js
atom.packages.getActivePackage('parinfer') // undefined
atom.packages.getActivePackage('Parinfer') // Package {path: "/home/geksilla/.atom/packages/Parinfer", metadata: Object
```
From the proton side we need to avoid usage of atom's api and rewrite couple of methods. Or create an issue in the `atom` repo.

@quarterto as workaround you can add `:Hydrogen` to `.proton` it should works fine.

**Comment by dvcrn** [comment]
fixed in latest master
