### ISSUE TITLE
Setting customFileTypes

### ISSUE THREAD

**Issue by kibin** [dvcrn/proton#209]
How can one set something like [this](https://github.com/atom/atom/issues/1718#issuecomment-179257487) with proton (what I want to achieve is forcing atom to always parse js files as jsx)?

```coffeescript
core:
    customFileTypes:
        "source.js": [
            "js-semantic"
        ]
```

I’ve tried this:
```clojure
    ["proton.core.customFileTypes" {"source.js" ["jsx"]}]
```
But had no luck.

**Comment by geksilla** [comment]
@kibin remote `proton.` from config name. It should be like 
```clj 
["core.customFileTypes" {"source.js" ["jsx"]}]
```

**Comment by kibin** [comment]
@geksilla ah, I’m so stupid, thanks. Anyway, this doesn’t work, neither is
```clojure
["core.customFileTypes" {"source.js" ["JavaScript (JSX)"]}]
```
Maybe it’s problem with atom itself.

**Comment by geksilla** [comment]
@kibin, np. Also I think that you have to specify file extension *"jsx"* instead of grammar name *"JavaScript (JSX)"*. Take a look for this packages which helps you to switch grammar you need.
* [set-syntax](https://atom.io/packages/set-syntax)
* [file-types](https://atom.io/packages/file-types)

**Comment by kibin** [comment]
Yeah, I’ve tried both jsx and grammar name, but with no luck. Thanks for the links, will look at them

**Comment by thuringia** [comment]
@geksilla Sorry for bringing this up again, but I cannot get proton to set multiple file types.
I have tried
```cljs
["core.customFileTypes" [ 
  {"source.gfm" ["diviner"]}
  {"source.json" ["book"]}]]
```
and variants like duplicating the setting but I get at most one of them to work.
Could you please give me a hint, I'm rather unfamiliar with Clojure(script) literals so I feel like missing something very obvious.

**Comment by geksilla** [comment]
@thuringia, no problem. To set multiple types atom expects that value will be an object with key source type and value list of grammars.
So you need to pass an object which is a hash map in clojurescript and its syntax very close to js object:
```javascript
// js
{
  "source.gfm": ["diviner"],
  "source.json": ["book"]
}
```
```clojure
;; clojure
{
  "source.gfm" ["diviner"]
  "source.json" ["book"]
}
```

In your case config will be:

```clojure
 ["core.customFileTypes"
  {"source.js" ["diviner"]
   "source.gfm" ["some"]}]
```

**Comment by thuringia** [comment]
That was the only variant I did not try. Thanks for the tip
