### ISSUE TITLE
LaTeX formatting with Markdown

### ISSUE THREAD

**Issue by Quixoticelixer** [dvcrn/proton#220]
The current default markdown preview plugin doesn't appear to support Latex Equations.

 e.g
$ 1 + 2 = {6 \over 2} $

**Comment by dvcrn** [comment]
This is something that belongs to the markdown preview plugin repo and not proton. There are some open issues [here](https://github.com/atom/markdown-preview/search?q=latex&type=Issues&utf8=✓) but besides that, nothing much proton can do here.

**Comment by Quixoticelixer** [comment]
What about changing preview plugin to markdown-preveiw-plus instead?

**Comment by dvcrn** [comment]
That could work. Similar to vim, we could add a `markdownProvider` setting to swap markdown-preview with markdown-preview-plus.

As always, pull requests are welcome :smile:
