### ISSUE TITLE
Julia mode with Juno

### ISSUE THREAD

**Issue by swt30** [dvcrn/proton#223]
I'm starting this issue to mention that development of Julia tooling in Atom seems to be converging on [Juno](http://junolab.org/). As well as the packages currently included in the julia layer, it also uses these two:

```
:tool-bar
:uber-juno
```

although I think uber-juno is just a meta-package that installs all the others. The keybindings also need updating, especially now that new features like debugging are arriving. When I next have time, I will try to take a look at updating the layer, but anyone else is also welcome to give it a crack :)

**Comment by dvcrn** [comment]
Sounds good to me. Pinging @spencerlyon2 since julia was his baby

**Comment by spencerlyon2** [comment]
@dvcrn thanks for the ping.

@swt30 it would be great to have this updated!

**Comment by spencerlyon2** [comment]
One concern is that tool-bar is an optional part of juno. I personally don't use it. If we do decide to add it to the layer I think it should be optional. 

Perhaps it can be set up in a way similar to the linters where there is a core linter layer and language specific layers only install their listing packages if the core linter layer is active.

**Comment by swt30** [comment]
Perhaps the tool bar has a toggle that we can include a key binding for. 

It looks like uber-juno is not needed if the other packages are installed individually. In fact, installing it without the others will just result in a confusing situation where proton and uber-juno start uninstalling and installing the same packages,

**Comment by spencerlyon2** [comment]
I agree that uber-juno should not be included in the layer.

I don't think I was very clear earlier in my tool-bar comment. What I meant is that the tool-bar package should not be forcibly installed by the Julia layer. It would be better to have tool-bar in its own layer and only activate Julia-specific toolbar features if that layer is active.

**Comment by swt30** [comment]
That sounds reasonable, as it is not really a core part of Juno but just provides access to its features. I think the first thing to do is review the keybindings and add any missing features, while leaving the tool bar for now. Julia 0.5 is coming in a few weeks so it is probably worthwhile putting off any major changes until then, as it will bring debugging and probably other goodies once the dev branch of Juno is merged.

**Comment by swt30** [comment]
Looks like atom-julia-client now includes debugging commands. I haven't quite been able to get the breakpoints to work yet though.

**Comment by swt30** [comment]
Julia 0.5 is out! I have been taking a look at the current keybindings and the new features in Juno and thinking about how best to arrange the functionality under `SPC m`. Some initial ideas are in [this gist](https://gist.github.com/swt30/55a5a604e0a8ed0c1bea4a04456c675a). I haven't been able to get debugging working yet but I will be taking a closer look at this when I have time.

**Comment by swt30** [comment]
It's years later, Juno unsurprisingly end up moving to vscode and I'm tidying my list of active issues, so I'll close this.
