### ISSUE TITLE
Question: Autocomplete keybindings

### ISSUE THREAD

**Issue by vladra** [dvcrn/proton#224]
I'm trying to remove ability to autocomplete on Enter. I've configured it via proton with `["autocomplete-plus.confirmCompletion" "tab"]` and when I go to UI configuration it seems only tab is selected, so config line is correct. But it still autocompletes also on Enter.

I was wondering if this Proton problem? How can I override this behaviour. I wanted to disable autocomplete default keybindings to fix this, but there is no documentation how should I specify keybindings in proton file.

Thanks in advance

update:

I managed to change config using these keybindings, but using autocomplete built in configuration it is not working

``` clojure
{:selector "atom-workspace atom-text-editor.autocomplete-active" :keymap [["enter" "editor:newline"]]}
{:selector "atom-workspace atom-text-editor.autocomplete-active:not([mini])[data-grammar~='gfm']" :keymap [["enter" "editor:newline"]]}
```

**Comment by dvcrn** [comment]
Do you have the elixir layer enabled by chance? I debugged this a bit and it seems like this is a issue with the `atom-elixir` package. I created a issue for it [here](https://github.com/msaraiva/atom-elixir/issues/44)

**Comment by vladra** [comment]
Yep, I have elixir package. Not using it atm though. Thanks for the tip
