### ISSUE TITLE
Terminal layer is broken

### ISSUE THREAD

**Issue by lowski** [dvcrn/proton#225]
On latest version of Atom `Terminal plus` is not working (terminal window opens blank with cursor blinking all the time). There are a lot of issues reported on the [Terminal plus GitHub issues page](https://github.com/jeremyramin/terminal-plus/issues/). People recommend to switch to [platformio-ide-terminal](https://atom.io/packages/platformio-ide-terminal) which is build based on `Terminal plus` and more active.

Is this something you consider?

**Comment by dvcrn** [comment]
Thanks for reporting! 
I will check platformio-ide-terminal but please, if this is something you would like to see in proton fast, feel free to submit a PR. Swapping out the packages would be as easy as changing the required packages inside the layer and rebinding the shortcuts

**Comment by lowski** [comment]
@dvcrn thanks for the response. I haven't looked how to develop layers with proton yet.

Sorry for OT but have you considered es6 instead of clojurescript?  I believe it will be easier to contribute for others. Clojurescript is still not very popular and installing lein and JVM is a little bit overkill to me.

The project is great but clojurescript can be a barrier for contributors.
