### ISSUE TITLE
Create keymap containing a chain of Vim-commands

### ISSUE THREAD

**Issue by richarddewit** [dvcrn/proton#229]
Is it possible to create a keybinding which executes a chain of Vim-commands? 

In Spacemacs I quite often use <kbd>SPC c y</kbd> which does a yank, comment, paste (duplicates line(s) and comments one (or selected ones) out).

I thought I'd re-create it, like I did in my .vimrc (`<Leader>` is <kbd>SPC</kbd>):

    nmap <Leader>cy yy:TComment<Cr>p
    vmap <Leader>cy ygv:TComment<Cr>`>p

but I have no idea how I would do that in `.proton`..

**Comment by jessejanderson** [comment]
Ooh, that _would_ be handy.

**Comment by dvcrn** [comment]
If you mean adding custom commands to the proton chain, that is actually already working. It's just nowhere documented so it's hard to know unless you worked on the project. This should definitely be part of the usage guide - https://github.com/dvcrn/proton/issues/228

Inside `.proton` is a key called `:keybindings`. You can add things to it in the normal layer-keybinding syntax. Example:

```
  ;; Don't like a keybinding or want to add something yourself? Do it here
  :keybindings {:c {:category "github"
                    :y {:title "test"
                        :action "hello"}}}
```

This renames category `c` to github (or creates it if it doesn't exist)  and adds a `y` action with title `test` that executes "hello".

**Comment by dvcrn** [comment]
I added a small example to the default `.proton` file to make it more clear. This definitely still needs a proper documentation

**Comment by geksilla** [comment]
I think the question here is about how to assign multiple commands for one keybinding. Unfortunately there is no support in atom for this case. The only way to chain commands is to write code in your `init.coffee` file. For more details check [here](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#composed-commands)

**Comment by richarddewit** [comment]
Ok I've written a custom script in `init.coffee`:

```
atom.commands.add 'atom-text-editor', 'custom:copy-and-comment-lines', ->
  editor = atom.workspace.getActiveTextEditor()
  editorView = atom.views.getView(editor)

  # Only does one line for now
  atom.commands.dispatch(editorView, 'vim-mode:yank-line')
  atom.commands.dispatch(editorView, 'editor:toggle-line-comments')
  atom.commands.dispatch(editorView, 'vim-mode:put-after')
```

And assigned it to `SPC c y`:
```
;; Don't like a keybinding or want to add something yourself? Do it here
:keybindings {
  :c {:category "comments"
      :y {:action "custom:copy-and-comment-lines" :title "copy and comment lines"}}
  . . .
}
```

But when I execute the key sequence, nothing happens.
When I run the command form the command palette (`SPC :`), then it works. What's wrong here? Init script loaded after proton?

**Comment by geksilla** [comment]
@richarddewit you need to specify `:target "atom-text-editor"` for your action, because added command will be dispatched on `atom-text-editor` selector.
```clj
 :y {:action "custom:copy-and-comment-lines" :title "copy and comment lines" :target "atom-text-editor"}
```

**Comment by richarddewit** [comment]
Thanks, will try this Monday

**Comment by richarddewit** [comment]
It works, thanks! Recap:

Write custom script in `init.coffee`:

```
atom.commands.add 'atom-text-editor', 'custom:copy-and-comment-lines', ->
  editor = atom.workspace.getActiveTextEditor()
  editorView = atom.views.getView(editor)

  # Only does one line for now
  atom.commands.dispatch(editorView, 'vim-mode:yank-line')
  atom.commands.dispatch(editorView, 'editor:toggle-line-comments')
  atom.commands.dispatch(editorView, 'vim-mode:put-after')
```

And assign it to `SPC c y`:

```
;; Don't like a keybinding or want to add something yourself? Do it here
:keybindings {
  :c {:category "comments"
        :y {:action "custom:copy-and-comment-lines" :title "copy and comment lines" :target "atom-text-editor"}}
  . . .
}
```
