### ISSUE TITLE
LaTeX / PDF View Package

### ISSUE THREAD

**Issue by karlmoller** [dvcrn/proton#230]
Maybe I am missing something, but how do I configure the lang/latex layer to open a PDF in PDF View (pdf.js) (rather than the system PDF viewer)? I can set it in the latex package settings, but obviously that gets wiped when proton loads. I read some of the source code (as much Clojure as I understand...) to see if there is some exposed hook, but I don't see anything.

**Comment by karlmoller** [comment]
New manual explains how to get this working. Closing.

**Comment by dvcrn** [comment]
Are you referring to the new manual.md file of proton? If yes how did it help you solve the problem?

**Comment by karlmoller** [comment]
Yes, I was not sure how to translate  keyspace + attribute in JS to Proton/Clojure the "correct way", the new manual.md explicitly states how it works. I eventually stumbled upon set-config! and hacked it in somewhere,  guess I should have taken the extra 15min to read more of the codebase.
