### ISSUE TITLE
additional-package seems to be reinstalled on startup 

### ISSUE THREAD

**Issue by karlmoller** [dvcrn/proton#231]
I am adding a non-layer additional package (Hydrogen) as follows to .proton:

:additional-packages
  [
    :hydrogen
  ]

Every time I start up Atom, it states that it is installing 1 new package: hydrogen and it takes a while for Atom to start. Other additional-packages don't seem to cause the same behaviour.

**Comment by dvcrn** [comment]
Do you know if hydrogen has other dependencies that it installs?

Open the shell and try `apm install hydrogen` to see if it fails or suceeds

**Comment by karlmoller** [comment]
apm install hydrogen
Installing hydrogen to /Users/karl/.atom/packages ✓

Seems to install fine. Also it works fine after it starts up. I don't see any other atom package dependencies. It requires zeromq and jupyter on the system. 
Link to hydrogen project: https://github.com/nteract/hydrogen

**Comment by geksilla** [comment]
looks like this issue related to #204.

**Comment by karlmoller** [comment]
Ah yes same problem, sorry for new issue!

**Comment by geksilla** [comment]
can you try to add this package capitalized like `:Hydrogen`?

**Comment by karlmoller** [comment]
That does seem to solve the problem.

**Comment by dvcrn** [comment]
Then it is the case problem again. We currently do a normal atom comparison between user package <-> installed packages without thinking about the case. Need to always downcase this

**Comment by geksilla** [comment]
@dvcrn, lets close this one and left #204 to track it?

**Comment by dvcrn** [comment]
sounds good to me!
