### ISSUE TITLE
Setting Ruby Path

### ISSUE THREAD

**Issue by andyrewlee** [dvcrn/proton#241]
Started getting this error today

`exec error: Error: Command failed: ~/.gem/ruby/2.3.0/bin/rsense start --port 47367 --path `

I was wondering if there was a way to change the gem filepath to something else. Mine is located somewhere else. Thanks for the help.

**Comment by dvcrn** [comment]
Take a look at https://github.com/dvcrn/proton/tree/master/src/cljs/proton/layers/lang/ruby#configuration and give the option `ruby-linter.rubyExecutablePath` a try. 

Besides that, this isn't proton specific and seems to come from the rsense plugin. If the method above didn't work, I'd suggest checking the config options there to find out how to configure it!

**Comment by andyrewlee** [comment]
thank you for the help!

**Comment by dvcrn** [comment]
How did you end up fixing the problem?

**Comment by andyrewlee** [comment]
i didn't yet...hahaha i'll get around to it later. i'm so new to atom i don't even know what it means to check out atom-ruby-test and give `ruby-linter.rubyExecutablePath` is

**Comment by WilsonChiang** [comment]
@dvcrn I tried setting the ruby-linter path but still having an issue with rfsense where it tries to use the wrong ruby version.
