### ISSUE TITLE
Remove environment package

### ISSUE THREAD

**Issue by cweagans** [dvcrn/proton#248]
Noticed this got installed when I was trying Proton. The note on https://atom.io/packages/environment says it's no longer necessary.

**Comment by jpinnix** [comment]
Still getting this deprecation warning: "The environment package is deprecated. Use process.env directly instead. atom/atom#12562"

**Comment by dvcrn** [comment]
Apologies, must have forgotten to push a new release to apm. It's out now and the error should be gone :)
