### ISSUE TITLE
Space menu not appearing/workingin Atom 1.13.0

### ISSUE THREAD

**Issue by richarddewit** [dvcrn/proton#251]
Probably due to deprecations.

* DeprecationWarning: sys is deprecated. Use util instead.
* The environment package is deprecated. Use process.env directly instead. https://github.com/atom/atom/pull/12562

Not sure if those are relevant.

 I really miss my space menu :<

**Comment by jackcasey** [comment]
Just a note that might help debugging: Running `proton:toggle` in the command palette also does nothing. 
The proton initialisation splash screen looks fine and I can't see anything much in the javascript console.

**Comment by dvcrn** [comment]
I noticed that as well in the Beta and secretly hoped we would have more time before the release hits. 

I'll try to take a look what could be causing this!

cc @geksilla as well

**Comment by smldis** [comment]
Hello, I just decided to install proton at work but this issue is hitting me.
Fortunately in my Archlinux machine, repos are still using 1.12.9.
Some testing:
proton:toggle command is working in the setting page and in the tree window if focused. Not working in editor in normal mode.
I would like to help but I am totally new. Thank you!

**Comment by geksilla** [comment]
When I was testing proton with atom beta 1.13 the issue was that vim-plus keybindings dispatched first, so probably there are some changes introduced to key map system. I will try to take a look today.

**Comment by richarddewit** [comment]
I'm using regular vim-mode:

``` clojure
    ["proton.core.inputProvider" :vim-mode]
```

**Comment by geksilla** [comment]
Want to ask to test changes from #252. Let me know how is going.

**Comment by richarddewit** [comment]
Btw, for some reason the space menu does work in a settings tab..
And sorry, I am in no position to test it right now (at work)

**Comment by geksilla** [comment]
@richarddewit, it should works everywhere except text-editor.

**Comment by smldis** [comment]
I confirm that current version (13.1) that has #252 is not fixing this issue in the text-editor. Thank you.

**Comment by smldis** [comment]
Using vim-mode instead of vim-mode-plus circumvent the problem, which-key works in text-editor.

**Comment by geksilla** [comment]
@smldis, @dvcrn I will check it asap.

**Comment by geksilla** [comment]
Just updated atom to 1.13 and it works for me.
@smldis, do you use `proton-bin` package or manually compiled from this repo?
@dvcrn, I think you didn't recompile new version in `proton-bin` repo. I don't see changes for `lib/proton.js` in last 2 commits

**Comment by richarddewit** [comment]
I can confirm that which-key now works, but as previously mentioned I'm using regular vim-mode, so I don't know if it works for vim-mode-plus

**Comment by jackcasey** [comment]
0.13.2 seems to be working for me (with vim-mode-plus). Will report back if I notice anything not working today.

Thanks for the quick fix!

**Comment by dvcrn** [comment]
Closing this for now

**Comment by spbrien** [comment]
I am having this problem with Atom 1.14.3 and proton 0.13.2 as well as 0.14.1

**Comment by dvcrn** [comment]
@spbrien that's odd. The current HEAD is what's released as well. If you have time, could you try one more time to remove the self-compiled version and use the apm one?

**Comment by spbrien** [comment]
@dvcrn Uninstalled and reinstalled with apm and all seems well. Maybe the download was cached by apm previously? In any case, thanks for this update... working perfectly!

**Comment by zer09** [comment]
@dvcrn 
Sorry for bumping this up. But I am also getting the deprecated environment packages, I tried to remove it but the proton-mode is reinstalling it after reopening the atom and also linter v2 asking to install dependencies, after installing the dependencies when re-opening the atom again, the proton-mode will remove it.

I am using atom 1.15 x64 and proton-mode 0.14.1

BTW I am new to atom, I want to try spacemacs but cant get it, so I find alternative and found this.

Thanks

**Comment by dvcrn** [comment]
@zer09 pushing fix for this hopefully today

**Comment by zer09** [comment]
@dvcrn if I disable the environment package on proton config, does it will break something? I see that proton(v0.15) will install this package by default. Or I will just ignore the deprecated warning?

Thanks
