### ISSUE TITLE
SPC menu appears after slight delay

### ISSUE THREAD

**Issue by armed** [dvcrn/proton#264]
Hi,

I don't know whether this is intentional or not, but space menu appears after ~200-400ms delay when I press spacebar. Same delay on `shift-cmd-p`. With pure atom I didn't notice any delay. Is there any config for this?

**Comment by dvcrn** [comment]
Hey, there is [here](https://github.com/dvcrn/proton/tree/master/src/cljs/proton/layers/core). `proton.core.whichKeyDelay` is set to 0.4s by default

Try changing that and let me know if it solved it for you

**Comment by armed** [comment]
Yep solved. Thanks.
