### ISSUE TITLE
Freshly install atom and proton, linter v2 welcome notification is always showing up

### ISSUE THREAD

**Issue by zer09** [dvcrn/proton#267]
Actually I already posted this issue at the linter repo steelbrain/linter#1398

If  I disable all the package installed by proton and re-enable it again except the proton-mode it self, the welcome notification will stop showing up but if  I enable again the proton-mode the linter welcome notification will show again on every start-up.

Thanks

**Comment by dvcrn** [comment]
I just pushed 0.15 which includes the linter related merge requests. This should get rid of the problem. Can you confirm?

**Comment by zer09** [comment]
Thanks @dvcrn I can confirm it solves the problem.
