### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ravernkoh** [dvcrn/proton#282]
I want to know if this project is still actively maintained. It looks great but I'm not sure if there are still updates going to it.

**Comment by dvcrn** [comment]
The project is still very much alive, just the 2 core contributors (me and @geksilla) don't have much time lately to actively work on features. Proton is in a pretty stable state and a lot of people use it daily

**Comment by ravernkoh** [comment]
Ok! Thank you for creating this.
