### ISSUE TITLE
Atomatigit for git integration

### ISSUE THREAD

**Issue by quartz55** [dvcrn/proton#36]
I recently discovered this project through a Spacemacs tweet and I have to say it looks very promising. I'm an Emacs (and Vim) fanatic but I would also like to move into more modern software, specially for a text editor, so I'll see what I can do to help out with this project.

Anyways, after looking through Atom packages I found [atomatigit](https://github.com/diiq/atomatigit) which seems to be a form of git integration based on magit, being proton heavily influenced by spacemacs, I thought it would be a good choice :+1:

**Comment by dvcrn** [comment]
Looked at that one too but I decided to go with the most popular git plugin instead. 
Definitely something worth evaluating and seeing if it performs better. Right now I don't like git-plus at all.

**Comment by dvcrn** [comment]
`<spc> g s` is now bound to atomatigit
