### ISSUE TITLE
Add default terminal package.

### ISSUE THREAD

**Issue by geksilla** [dvcrn/proton#49]
I thinks we can add some terminal package to core layer and bind it to <kbd>SPC `</kbd>. I found few interesting packages:

https://atom.io/packages/terminal-panel
https://atom.io/packages/atom-terminal-panel
https://atom.io/packages/terminal-plus
https://atom.io/packages/term2
https://atom.io/packages/term3

I've tried all of them. And for now my choice is terminal-plus.

Feel free to propose another one and share your experience.

**Comment by dvcrn** [comment]
Hey! I agree that a terminal is probably nice to have. But I think it might be better in a separate `:term` or `:terminal` layer. 

I'm gonna check these out tomorrow :)

**Comment by geksilla** [comment]
Agree with separate layer. May be `:tools/terminal`?

**Comment by DanTheColoradan** [comment]
Any new thoughts here? From the screen captures, terminal-plus definitely looks the nicest.

**Comment by DanTheColoradan** [comment]
@geksilla if you have terminal-plus ready, could you create a pull request? Otherwise, let me know and I'll give it a shot.
