### ISSUE TITLE
Implement better pane management system

### ISSUE THREAD

**Issue by spencerlyon2** [dvcrn/proton#65]
The options for pane management in atom (especially the default ones) are less than stellar. 

A great feature from spacemacs is the numbered panes that allow you to easily navigate between open files with `spc #` where `#` is the pane number. 

Something like this in proton would be _amazing_!

**Comment by dvcrn** [comment]
Definitely possible but I couldn't find a plugin for this yet. 
We could use the atom API to find all panes (and map the side bar to 0), check if the panel with index # exists and then focus it. Shouldn't be too difficult :)

**Comment by spencerlyon2** [comment]
Yeah I've searched for plug-ins many times and tried all of what's out there. Nothing is as good (for me) as spacemacs 

If implementing this on our own isn't too hard,  I'd love to see it.

**Comment by dvcrn** [comment]
Seems like [this](https://atom.io/docs/api/v1.3.2/Workspace#instance-getPaneItems) is what we want

**Comment by dvcrn** [comment]
Just realised that we are still missing `SPC w m` for closing all other panes (or 'maximising' the current one)

**Comment by dvcrn** [comment]
One thing that I still have in my head is, how should we treat panes and windows? Should we treat them as normal atom panes or just 'display options' for buffers? 
E.g. in atom, closing a pane destroys all items with it. In emacs (spacemacs), closing a pane destroys the pane but leaves the buffers open. 

If we want the same behaviour, we need to move all tabs / buffers to the active pane when closing others. 

Besides that, are we missing anything here or can I close this?

**Comment by spencerlyon2** [comment]
I think closing buffers with a pane is fine.

It is likely that spacemacs keeps a buffer alive, because that is the emacs default. Here the atom default is to close them, so I don't see any harm in doing that.

I think we can close this, but we need to keep in mind the outstanding issues in #72 (a single `[0-9]` entry in keybinding list rather than 10, and labels on each pane so users know what number each pane is). I'll open issues for those items though.
