### ISSUE TITLE
Consistency with Spacemacs' evil-leader bindings?

### ISSUE THREAD

**Issue by dtreiter** [dvcrn/proton#67]
What are thoughts on keeping the keybindings close to what spacemacs has already done? It seems possible that someone may want to occasionally switch between using proton and spacemacs. Keeping the keybindings similar could keep the transition smoother.

That being said, not all of spacemac's bindings are necessarily ideal either.

**Comment by dvcrn** [comment]
We are trying to keep things similar but right now focus more on implementing new things. Though I agree that we should get some more strategy into the keybindings

**Comment by DanTheColoradan** [comment]
I do have to say though that I have found many of the new keybindings more intuitive or perhaps better organized.
