### ISSUE TITLE
Submit to atom packages

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/proton#7]
We might need a new name first since proton is already taken. Plus we need to check how we can submit a compiled version.

**Comment by geksilla** [comment]
We need to move *package.json* from *plugin* folder to root and edit **"main"** script location. To recompile plugin before publish we can use **"prebuplish"** hook script added to *package.json* here is some [info](https://docs.npmjs.com/misc/scripts#common-uses) regarding npm scripts hooks.

**Comment by dvcrn** [comment]
I was thinking about something simpler:

We just compile proton and push the plugin folder into a new "proton-binary" repository. That's what we are going to submit. 

I think pushing this repository to atom won't work because it would require us to either compile on the spot (which won't work because the majority of users don't have lein installed) or submit compiled files together with the uncompiled ones which is also kind of dirty. 

But then again, we can experiment with this and see which solution is more effective in the end

**Comment by geksilla** [comment]
@dvcrn I think that **prebuplish** hook is running locally so we can execute ```lein cljsbuild once dev```. After that source code with compiled version will be published.

**Comment by dvcrn** [comment]
Oh now I get it. I somehow read that as 'pre-commit', my bad! That could indeed work! 

But now we still need a better name. Proton sadly exists already https://atom.io/packages/proton

**Comment by dvcrn** [comment]
All right, I tried this approach and it sadly does not work. 

```
~/.atom/packages/proton-mode
λ tree
.
├── HOW-TO-LAYER.md
├── LICENSE.md
├── README.md
├── keymaps
│   └── proton.cson
├── package.json
├── project.clj
├── src
│   └── proton
│       ├── config
│       │   ├── editor.cljs
│       │   └── proton.cljs
│       ├── core.cljs
│       ├── layers
│       │   ├── base.cljs
│       │   ├── clojure
│       │   │   └── core.cljs
│       │   ├── core
│       │   │   └── core.cljs
│       │   ├── git
│       │   │   └── core.cljs
│       │   └── python
│       │       └── core.cljs
│       └── lib
│           ├── atom.cljs
│           ├── helpers.cljs
│           ├── package_manager.cljs
│           └── proton.cljs
├── styles
│   └── proton.less
└── templates
    └── proton.edn

12 directories, 20 files
```

It seems like apm just links the repository and does a fresh checkout. I think we need to go with the binary approach

**Comment by dvcrn** [comment]
Binary approach worked :) We are live at https://atom.io/packages/proton-mode. Bin repo is https://github.com/dvcrn/proton-bin

I went with `proton-mode` since proton was already taken and we don't have anything better yet. apm allows easy package renaming though so changing it later on shouldn't be a problem
