### ISSUE TITLE
`SPC esc` will quit proton-chain, but moves cursor forward

### ISSUE THREAD

**Issue by spencerlyon2** [dvcrn/proton#73]
I'm using `vim-mode` and when I press SPC to enter the chain I see that `vim-mode:move-right` is being called as the chain starts. 

Should we just un-map this?

**Comment by dvcrn** [comment]
Yep, un-mapping sounds good!

**Comment by geksilla** [comment]
:+1: to un-map, same issue with vim-mode-plus.

**Comment by dvcrn** [comment]
although we currently bind space through code here https://github.com/dvcrn/proton/blob/master/src/cljs/proton/core.cljs#L180. If we unbind SPC, this might not trigger anymore so we need to add a new keybinding inside the proton keymap. Something like `proton:dummy` so we can catch the keyboard event again.

**Comment by geksilla** [comment]
I prevent this issue in my `.proton`.

```clj
  :keymaps [{:selector "body atom-text-editor.vim-mode-plus:not(.insert-mode)" :keymap [["space" "proton:toggle"]]}
            {:selector "atom-text-editor.vim-mode:not(.insert-mode)" :keymap [["space" "proton:toggle"]]}]
```

**Comment by spencerlyon2** [comment]
Brilliant, this works for me also.

Maybe we should just build this into proton directly (include in the default keymaps, not just in the default template)?

**Comment by dvcrn** [comment]
Included it into proton core
