### ISSUE TITLE
nuclide-quick-open aborts installation process

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/proton#76]
Not sure how that happens but every time proton proceeds to install `nuclide-quick-open`, all packages after won't install. Need to restart the editor to continue package installations

**Comment by spencerlyon2** [comment]
Are you totally certain quick open even finishes installing?

When I install it via apm at the command line it takes a few minutes. Maybe you haven't waited long enough?

**Comment by dvcrn** [comment]
Closing in favor of https://github.com/dvcrn/proton/issues/101
