### ISSUE TITLE
Proton enables packages that should be disabled

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/proton#86]
Another oversight when I implemented this feature. 

Besides themes getting applied, I noticed that proton also force-activates packages that layers want to be disabled. As a test, just disable "relativeLineNumbers" inside .proton. The layer deactivates it but proton core activates it again. 

We need to find a solution in which we force-activate all packages that are needed but still allow layers to disable packages

**Comment by spencerlyon2** [comment]
Ahh I just noticed this the other day and was going to open an issue once I investigated more to find the issue.

Any thoughts on how to resolve?

**Comment by dvcrn** [comment]
1. We could blatantly enable everything before layer-init, but that would result that some of the needed packages are not there yet because the packages list could change after init. 

2. Layers could keep track if a package is disabled / enabled and remove it from `get-packages`

3. We tweak enable/disable to save the package state and filter all `disabled-packages` (by proton) with all packages that layers need

4. We provide a separate API that layers can use to disable / enable a package. Something like `mark-enabled` and `mark-disabled`. Core is then only enabling packages that are marked as enabled.

Just some thoughts

**Comment by geksilla** [comment]
I like 4.
> We provide a separate API that layers can use to disable / enable a package. Something like `mark-enabled` and `mark-disabled`. Core is then only enabling packages that are marked as enabled.

**Comment by geksilla** [comment]
@dvcrn, I made [experimental branch](https://github.com/geksilla/proton/tree/fix/enabled-packages-should-be-disabled) feel free to check it out.

**Comment by dvcrn** [comment]
@geksilla very nice. I'll see if I can use this!

**Comment by dvcrn** [comment]
Your change seem to have mostly fixed this. I am closing this issue.
